name: Pipeline
on: [push]

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: >
        cd BattleNetPrefill.Test;
        dotnet test --no-restore -c Release --filter "FullyQualifiedName!=BattleNetPrefill.Test.LogFileUpToDateTests&FullyQualifiedName!=BattleNetPrefill.Test.DownloadTests"
      
  Sonar-Analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan     
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          # Additional arguments for the sonarcloud scanner
          args:             
            -Dsonar.projectKey=tpill90_Battlenet-lancache-prefill
            -Dsonar.organization=tpill90