name: build-and-test
run-name: "Build and Test"
on: [push]

env:
  # Used to parameterize these build scripts between LancachePrefill projects
  PROJECT_NAME: BattleNetPrefill

jobs:
  build-test:
    uses: tpill90/lancache-prefill-common/.github/workflows/build-and-test.yml@main
    with:
      PROJECT_NAME: BattleNetPrefill
      DOTNET_TEST_FILTER: "TestCategory!=SkipCI"